### ISSUE TITLE
"expected to be a reference" warning

### ISSUE THREAD

**Issue by niccolox** [nuvoleweb/atrium_folders#1]
just installed Atrium Folders on OA beta 10 on Ubuntu 10.10 running Aegir and got this non-critical error

warning: Parameter 2 to notifications_content_form_alter() expected to be a reference, value given in /var/aegir/platforms/atrium-1.0-beta10/includes/common.inc on line 2892.

file dialog and drag-n-drop both gave error, but ignores and all good

thanks, great Feature !

**Comment by ademarco** [comment]
It looks like a Drupal core problem with PHP 5.3: 

http://drupal.org/node/925580

I'm afraid we have to wait for it to be fixed upstream.
