### ISSUE TITLE
Submit buttons hide

### ISSUE THREAD

**Issue by jmaties** [nuvoleweb/atrium_folders#10]
Submit buttons from toolbox is hide...
![Imagen](http://dl.dropbox.com/u/14093747/Captura%20de%20pantalla%202011-07-15%20a%20las%2015.52.50.png)

**Comment by jmaties** [comment]
ok, is not compatible with jquery_update :P

**Comment by joostvdl** [comment]
How is this solved now? I habe a default OA 1.0 install and buttons are hidden here.

**Comment by jmaties** [comment]
Uninstalling jquery_update

**Comment by ghost** [comment]
This should not be closed, but should be resolved and must be compatible with jQuery Update module.

**Comment by LudwigH** [comment]
I agree with pwoxisolutions. Folders is just what I needed to make Open Atrium work for me, however as I will be deploying on an external site and other modules I use use jQuery, Atrium Folders should be made compatible with jQuery Update module. I don't know how to do that myself…

**Comment by scullen** [comment]
I'm in this same situation with the missing buttons. If the jquerry_update module is disabled then some Open Atrium 1.0 features don't work, ie. dragging to customize dashboards. Disabling jquerry_update is not really an option to achieve full functionality.

**Comment by lyd70** [comment]
When I disable jquery_update the submit button on Atrium Folders works. However, I can no longer customize dashboards. This is a serious problem. How can this be solved?

**Comment by socialnicheguru** [comment]
Hi with the new version from nov 11, the issue is resolved.
