### ISSUE TITLE
Turning on jquery update with atrium 1.0 make Folders inputs invisble

### ISSUE THREAD

**Issue by bdawg8569** [nuvoleweb/atrium_folders#15]
When the Jquery update module is turned on, a "style='display:none'' is getting added to the buttons on the toolboxes to move and delete items. I can't see to figure out why.

**Comment by ghost** [comment]
Same issue here. I cannot figure it out as well. Help is needed here.

**Comment by emaV** [comment]
The button of modal toolbox are hidden by itweak_upload behaviors that is (re)attached to the modal div by ahah.prototype.success function.

Hopefully the ModalToolbox behaviors runs after itweak_upload so you can reset the submit buttons visibility there:

```
  // Show submit buttons in modal form (hidden by itweak_upload)
  $('#modal-content .buttons input[type="submit"]:not(.modal-toolbox-processed)').show().addClass('modal-toolbox-processed');
```

**Comment by ademarco** [comment]
Thanks @emaV just pushed your changes, closing.
