### ISSUE TITLE
Cannot see Atrium Folders module

### ISSUE THREAD

**Issue by dougmckown** [nuvoleweb/atrium_folders#26]
I placed nuvoleweb-atrium_folders-5412600 (extracted folder) in users/dougmckown/Sites/Atrium-1.1/sites/all/modules/features. (The path looks like this: users/dougmckown/Sites/Atrium-1.1/sites/all/modules/features/nuvoleweb-atrium_folders-5412600). I logged out of Open Atrium, stopped Aquia Drupal Stack, restarted Aquia Drupal Stack, logged in to Open Atrium, and navigated to Settings > Customize Features. I do not see the Atrium Folders listed as a module/feature. 

Am I missing something? Should the folder be renamed? Can anyone help? Thanks!

Doug McKown
twitter.com/dougmckown
dougmckown (at) gmail (dot) com

**Comment by ademarco** [comment]
You should first enable it as a normal module and then as a feature from inside a group.

**Comment by dougmckown** [comment]
Thanks for your reply. Where/how do I enable it as a normal module first?

**Comment by dougmckown** [comment]
Message for other newbies who have encountered the same problem: Click the Administer link in the bottom corner > click the Modules link (within the Site Building section) > scroll to the Features section > enable the Atrium Folders box > click Save Configuration (at the bottom of the screen) > go back to your group > click Settings > Customize Features > set Atrium Folders to Enabled > click Save for {group name} at the bottom of the page.
