### ISSUE TITLE
Missing text in 'Notifications' button

### ISSUE THREAD

**Issue by joepstender** [nuvoleweb/atrium_folders#3]
The 'Notifications' button does not contain text. I'm using a Dutch translated version of OA.  Check screenshot: http://db.tt/m4a7yue

**Comment by selkie** [comment]
Same problem here. Did you understand what the problem was?

**Comment by selkie** [comment]
I understand the reason of the missing text. You have to check if at yoursite/admin/messaging/notifications/events the notification events are enabled.
