### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by alphakamp** [nuvoleweb/atrium_folders#4]
Anonymous users can change folder settings even when anonymous users are given no permissions.  Permissions for all users seems to be ignored.

**Comment by nuvoleweb** [comment]
Thanks for reporting. Access control is bypassed in case the group is public and "access content" permission is granted for anonymous, is this your case? I've pushed basic access control that should prevent it to happen again.

**Comment by alphakamp** [comment]
That did exactly what I wanted. And yes the group was public.  Thanks for responding so fast.

**Comment by kaho-kimvm** [comment]
I'm having an identical issue but in my case it's a private group with the ability to access content for authenticated user. But I do not understand what you mean by 'I've pushed basic access control that should prevent it to happen again'. I've cloned the latest version of atrium_folders.
